spring.application.name=BookManagementSystem

spring.data.mongodb.uri=mongodb://localhost:27017/book_management_db

server.port=8080

spring.thymeleaf.cache=false

spring.data.mongodb.auto-index-creation=true